spring.application.name=service

app.metrics.batch.interval-ms=270000
app.metrics.types=INFO,WARN,error,TEST

spring.kafka.bootstrap-servers=kafka-ls:9092
spring.kafka.consumer.group-id=log-santos-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.type.mapping=event:com.bigsmo.common.model.NormalizedLogEvent,metric:com.bigsmo.common.dto.LogMetricEvent

app.kafka.topics.raw-logs=raw-logs-topic
app.kafka.topics.normalized-logs=normalized-logs-topic
app.kafka.topics.metrics=metrics-topic