apiVersion: 1

datasources:
  - name: Elasticsearch-Logs
    type: elasticsearch
    uid: elasticsearch
    url: http://elasticsearch:9200
    access: proxy
    isDefault: false
    jsonData:
      index: "logs-*"
      timeField: "@timestamp"
      esVersion: "8.19.6"
      logMessageField: message
      logLevelField: level
    editable: true

  - name: ClickHouse-Metrics
    type: grafana-clickhouse-datasource
    uid: clickhouse
    url: http://clickhouse:8123
    access: proxy
    jsonData:
      defaultDatabase: logger
      port: 8123
      server: clickhouse
      username: grafana
      password: grafana_pass
      tlsSkipVerify: true
    editable: true