apiVersion: 1

datasources:
  - name: Elasticsearch-Logs
    type: elasticsearch
    uid: elasticsearch
    url: http://elasticsearch-ls:9200
    access: proxy
    isDefault: false
    jsonData:
      index: "log_event"
      timeField: "@timestamp"
      esVersion: "8.19.6"
      logMessageField: message
      logLevelField: level
    editable: true

  - name: ClickHouse-Metrics
    type: grafana-clickhouse-datasource
    uid: clickhouse
    url: http://clickhouse-ls:9000
    access: proxy
    jsonData:
      defaultDatabase: logsantos
      port: 9000
      server: clickhouse-ls
      username: default
      password: 123
      tlsSkipVerify: true
    editable: true
