{
 "title": "LogSantos Metrics Dashboard",
 "tags": [
  "log-santos",
  "metrics"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "ALL LOGS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT windowStart as time, sum(value) as total FROM logsantos.metrics WHERE metricName = 'logs_total' GROUP BY time ORDER BY time"
    }
   ]
  },
  {
   "title": "ERROR",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT windowStart as time, sum(value) as errors FROM logsantos.metrics WHERE metricName = 'logs_error' GROUP BY time ORDER BY time"
    }
   ]
  },
  {
   "title": "WARN",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT windowStart as time, sum(value) as warnings FROM logsantos.metrics WHERE metricName = 'logs_warn' GROUP BY time ORDER BY time"
    }
   ]
  },
  {
   "title": "INFO",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT windowStart as time, sum(value) as info FROM logsantos.metrics WHERE metricName = 'logs_info' GROUP BY time ORDER BY time"
    }
   ]
  },
  {
   "title": "DEBUG",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT windowStart as time, sum(value) as debug FROM logsantos.metrics WHERE metricName = 'logs_debug' GROUP BY time ORDER BY time"
    }
   ]
  }
 ]
}